AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Create a Security Group
  Should be deployed on 
  https://devops-kuba.s3.eu-central-1.amazonaws.com/cloudformation/v6-nested-stacks-security-group.yml
  to be part of a nested stack in v6-nested-stack.yml
Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: Launch new instance in this VPC 
  SSHSourceIpRange:
    Description: The IP address range that can be used to SSH to the EC2 instances
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
Resources:
  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      VpcId: !Ref VpcId
      GroupDescription: Enable SSH access via port 22 and HTTP via port 80
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: !Ref SSHSourceIpRange
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: 0.0.0.0/0
Outputs:
  SecurityGroupId:
    Value: !Ref InstanceSecurityGroup
